# Generated by Django 4.0.4 on 2022-05-22 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('Id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('GPA', models.DecimalField(decimal_places=2, max_digits=4)),
                ('phone', models.CharField(max_length=11)),
                ('mail', models.CharField(max_length=50)),
                ('birthday', models.DateField()),
                ('Gender', models.CharField(choices=[('1', 'Male'), ('2', 'Female')], default='1', max_length=1)),
                ('State', models.CharField(choices=[('1', 'Active'), ('2', 'Inactive')], default='1', max_length=1)),
                ('level', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='1', max_length=1)),
                ('department', models.CharField(choices=[('1', 'General'), ('2', 'CS'), ('3', 'DS'), ('4', 'AI'), ('5', 'IS'), ('6', 'IT')], default='1', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
