# Generated by Django 4.0.4 on 2022-05-22 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='GPA',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='student',
            name='Gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='1', max_length=6),
        ),
        migrations.AlterField(
            model_name='student',
            name='State',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='1', max_length=8),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('General', 'General'), ('CS', 'CS'), ('DS', 'DS'), ('AI', 'AI'), ('IS', 'IS'), ('IT', 'IT')], default='1', max_length=8),
        ),
    ]
