# Generated by Django 4.0.4 on 2022-05-22 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0002_alter_student_gpa_alter_student_gender_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['Id']},
        ),
        migrations.AlterField(
            model_name='student',
            name='Gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Female', max_length=6),
        ),
        migrations.AlterField(
            model_name='student',
            name='State',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=8),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('General', 'General'), ('CS', 'CS'), ('DS', 'DS'), ('AI', 'AI'), ('IS', 'IS'), ('IT', 'IT')], default='General', max_length=8),
        ),
    ]
