# Generated by Django 4.0.4 on 2022-05-22 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0003_alter_student_options_alter_student_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='GPA',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='student',
            name='Id',
            field=models.CharField(default='0', max_length=8, primary_key=True, serialize=False),
        ),
    ]
