# Generated by Django 4.0.4 on 2022-05-24 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0007_alter_student_birthday_alter_student_department_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
