# Generated by Django 4.0.4 on 2022-05-24 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='passwordd',
        ),
    ]
